image: ubuntu:22.04

stages:
  - lint
  - format
  - build

# Lint-Check: Checks if the code is correctly formatted
lint:
  stage: lint
  script:
    - apt-get update && apt-get install -y clang-format
    - echo "Running clang-format lint check..."
    - find . -regex '.*\.\(c\|h\)' -exec clang-format --dry-run --Werror {} +
  only:
    - merge_requests
  allow_failure: true # Stop on errors

# Clang-Tidy: Performs static analysis on the code
clang-tidy:
  stage: lint
  script:
    - apt-get update && apt-get install -y clang-tidy
    - echo "Running clang-tidy..."
    - find . -regex '.*\.\(c\|h\)' -exec clang-tidy {} -- -I. \;
  only:
    - merge_requests
  allow_failure: true

# Formatting: Performs automatic formatting
format:
  stage: format
  script:
    - apt-get update && apt-get install -y clang-format
    - echo "Running clang-format on all source files..."
    - find . -regex '.*\.\(c\|h\)' -exec clang-format -i {} +
  only:
    - merge_requests
  allow_failure: false

build:
  stage: build
  script:
    - echo "Building the project..."
    # - make for later Makefile
  only:
    - merge_requests
    - branches
