image: ubuntu:22.04

stages:
  - lint
  - format
  - build

# Lint-Check: Überprüft, ob der Code korrekt formatiert ist
lint:
  stage: lint
  script:
    - apt-get update && apt-get install -y clang-format
    - echo "Running clang-format lint check..."
    - find . -regex '.*\.\(c\|h\)' -exec clang-format --dry-run --Werror {} +
  only:
    - merge_requests
  allow_failure: false # Stopp bei Fehlern
  allow_failure: false

clang-tidy:
  stage: lint
  script:
    - apt-get update && apt-get install -y clang-tidy
    - echo "Running clang-tidy..."
    - find . -regex '.*\.\(c\|h\)' -exec clang-tidy {} -- -I. \;
  only:
    - merge_requests
  allow_failure: false

# Formatierung: Führt die automatische Formatierung durch
format:
  stage: format
  script:
    - apt-get update && apt-get install -y clang-format
    - echo "Running clang-format on all source files..."
    - find . -regex '.*\.\(c\|h\)' -exec clang-format -i {} +
  only:
    - merge_requests
  allow_failure: false # Falls der Formatierungsschritt scheitert, wird der Merge-Request blockiert
  allow_failure: false

build:
  stage: build
  script:
    - echo "Building the project..."
    # - make für späteres Makefile
  only:
    - merge_requests
    - branches
